from game_management.views.main import *
from game_management.views.bot import *
from game_management.views.masters import *
from game_management.views.members import *
from game_management.views.promo import *
from game_management.views.schedule import *
from game_management.views.rating import *
from game_management.views.glossary import *
from game_management.views.results import *
from game_management.views.location import *