# Generated by Django 4.1.5 on 2023-01-23 21:41

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_management', '0004_alter_location_direction_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='direction_photo',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='files/directions'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_photo',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='files/locations'), upload_to=''),
        ),
    ]
