# Generated by Django 4.1.5 on 2023-01-25 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_management', '0006_rename_location_directions_location_location_directions'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='promo_date',
            field=models.DateField(default=datetime.date(2023, 1, 25)),
        ),
    ]
