# Generated by Django 4.1.5 on 2023-01-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_management', '0007_promo_promo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tg_id',
            field=models.BigIntegerField(default=0, max_length=20),
        ),
    ]
