# Generated by Django 4.1.5 on 2023-01-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_management', '0009_alter_member_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='promo',
            name='promo_type',
            field=models.CharField(default='О нас', max_length=30),
        ),
    ]
