# Generated by Django 4.1.5 on 2023-01-28 12:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game_management', '0010_promo_promo_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(default=0)),
                ('tg_name', models.CharField(max_length=255)),
                ('tg_first_name', models.CharField(blank=True, default='', max_length=255)),
                ('tg_last_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('tg_name2', models.CharField(blank=True, default='', max_length=255)),
                ('lead_date', models.DateField(default=None, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='tg_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='tg_name',
        ),
        migrations.AddField(
            model_name='member',
            name='registered_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='LeadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime(2023, 1, 28, 15, 48, 19, 674836))),
                ('log_type', models.CharField(blank=True, max_length=40, null=True)),
                ('lead', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_management.lead')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game_management.member')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game_management.lead'),
        ),
    ]
