# Generated by Django 4.1.5 on 2023-01-28 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_management', '0011_lead_remove_member_tg_id_remove_member_tg_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='tg_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leadlog',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 16, 26, 1, 217003)),
        ),
    ]
