# Generated by Django 4.1.5 on 2023-04-01 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_management', '0013_lead_phone_no_alter_leadlog_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadlog',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 1, 14, 12, 46, 919323)),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_birth',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
